# Generated by Django 6.0.2 on 2026-02-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('location', models.CharField(help_text='Ville/Quartier', max_length=200)),
                ('preferred_payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('nita', 'Nita (Transfert bancaire)')], max_length=20)),
                ('product_types', models.TextField(help_text='Types de produits que vous vendez')),
                ('business_description', models.TextField()),
                ('id_document', models.FileField(blank=True, null=True, upload_to='seller_requests/documents/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text="Notes de l'administrateur")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Vendeur',
                'verbose_name_plural': 'Demandes Vendeurs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
