# Generated by Django 6.0.2 on 2026-02-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_at',
            new_name='delivery_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery_confirmed',
            field=models.BooleanField(default=False, help_text='Client a confirmé la réception'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payment_released',
            field=models.BooleanField(default=False, help_text='Argent libéré au vendeur'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payment_verified',
            field=models.BooleanField(default=False, help_text='Admin a vérifié le paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('nita', 'Nita (Transfert bancaire)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Capture/reçu de paiement', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Référence de transaction', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'En attente de paiement'), ('payment_received', 'Paiement reçu (Escrow)'), ('in_preparation', 'En préparation'), ('in_delivery', 'En livraison'), ('delivered', 'Livrée'), ('dispute', 'Litige'), ('cancelled', 'Annulée')], default='awaiting_payment', max_length=20),
        ),
    ]
