# Generated by Django 6.0.2 on 2026-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_paid_at_order_delivery_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission en pourcentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant pour le vendeur (après commission)', max_digits=10),
        ),
    ]
